# Generated by Django 4.1.2 on 2024-07-03 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camionetas', '0001_initial'),
        ('motos', '0001_initial'),
        ('autos', '0001_initial'),
        ('concesionario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='repuesto',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='vehiculo',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='categoria',
            field=models.CharField(choices=[('auto', 'Auto'), ('moto', 'Moto'), ('camioneta', 'Camioneta')], default='vehiculo', max_length=20),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='vehiculo_auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='autos.auto'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='vehiculo_camioneta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camionetas.camioneta'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='vehiculo_moto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='motos.moto'),
        ),
        migrations.DeleteModel(
            name='CarritoCompras',
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
        migrations.DeleteModel(
            name='Repuesto',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
